### ISSUE TITLE
[FEATURE] Specify HTML title on command line

### ISSUE THREAD

**Issue by 0x15e** [madushans/DependenSee#11]
This is a pretty simple request and I'm happy to submit a PR for it but wanted to talk to you about how best to go about it.

I would like to be able to specify the title used in HTML output from the command line. I'm currently going through a lot of projects trying to find dependencies and sometimes end up with multiple DependenSee HTML browser windows open and it would be helpful to be able to tell them apart more easily.

An option could be added such as `-HT` or `-HtmlTitle` where it defaults to "DependenSee" (current behavior) if not specified. The option could be ignored for mismatched output types, a warning displayed but output still generated, or an error + abort triggered.

My approach would be to add new constants in `ResultWriter.cs` for `HtmlTitleToken` and `HtmlTitleDefault` and then make the necessary updates in `PowerArgsProgram.cs`, `Program.cs`, `ResultWriter.Write`, and `ResultWriter.WriteAsHtmlToFile` to support passing the value through and applying it. The value would be appropriately escaped before being injected into the HTML output.

I also considered using something like AngleSharp to make the update since it's HTML but that seems like overkill as long as the value is being escaped properly.

I don't intend to modify XML, JSON, or GraphViz output as I am less familiar with their use cases and wouldn't want to make changes that could break anyone else's workflow.

I look forward to hearing your thoughts on this.

**Comment by madushans** [comment]
Yep this sounds good.

Escaping can be done with [WebUtility.HtmlEncode](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.htmlencode?view=net-5.0).

Can ignore the option if the `-OutputType` is not `HTML` . This is consistent with  `-OutputPath` which is ignored when the `-OutputType` is a Console output.

May be we should look into treating each output type as a sub command, but that would break backwards compatibility, so I can think about doing that later separately.

If you're happy to do a PR, I look forward to it. Otherwise I can implement it, though it may take a few weeks for me to find the time.

If you're doing a PR, please branch from `dev` and also update the [version number here](https://github.com/madushans/DependenSee/blob/4decc1f2e90e0f336de36e8a1557a452100e93bd/DependenSee/DependenSee.csproj#L10) to increment the minor version.

**Comment by 0x15e** [comment]
Sounds good. I'll start on it and should have a PR for you either today or tomorrow.

**Comment by madushans** [comment]
Your changes are [now available on Nuget](https://www.nuget.org/packages/DependenSee/1.3.0). 

Thanks you for your contribution and thank you again for using DependenSee ♥
