### ISSUE TITLE
[FEATURE] Show classes inside project

### ISSUE THREAD

**Issue by modestotech** [madushans/DependenSee#46]
Apparently the tool only shows dependencies on the project/nuget level. I'd like to be able to drill into a project to see the class dependencies inside that specific project.

**Comment by madushans** [comment]
Hey this is a good question.
I have thought about adding class dependencies. But it brings a few issues. Short answer is, I've decided not to address these problems due to their complexity, and the fact that this is a hobby project. If this is required, the best option is to use a commercial product like VS Architecture Map, or NDepend. They both solve this issue quite well. I don't intend to compete with them.

While not the same "graph" view, there's also [Depends](https://github.com/bjorkstromm/depends) project by @bjorkstromm which may work for you. It is also under the MIT license. (I don't know the project or the owner. Just a fan.)

## I've decided this is beyond the scope of DependenSee and will not be supported in the foreseeable future.

Anyway here are the main problems this pose, which above commercial solutions have addressed in different and opinionated ways.

- Detecting Classes
- Detection Dependencies
- Displaying Dependencies

# Detecting Classes
Currently DependenSee does not parse code, or inspect build artifacts. Current detection is based on msbuild inputs, specifically csproj and vbproj files. In fact it can run on a solution with no code, or code that doesn't compile.

But detecting classes will require atleast partially compiling the projects, likely via Roslyn, so we can see the classes, or run reflection on the build artifacts, requiring the right SDK and other things to be present and functional.

This alone should be possible after some work, though will need work specific to each language, where currently adding a new project type is relatively straightforward as they tend to be just looking for msbuild files with a different file extension.

# Detecting Dependencies

Once we have classes, we have to decide what we consider a dependency. This seem straightforward, but it really is not.

Given a class:
- Do we consider all other classes the class needs, as dependencies?
- Is the type of a property, a dependency? a constructor argument? a method argument? method return type?
- What about the super classes of those types? what about subclasses and/or implementations? i.e if a class accepts `IFileWriter` as a constructor arg, or as a property, should we look for all implementations of this interface? What if they come from other assembles or projects that are not available in the source set?
- What if these types are from a nuget package?
- What if they are internal or private? What if it is public, but implementation is not public?
- What if the current class and/or its resolved dependencies have generics? What if the generics are open, where they are resolved at runtime?
- ... probably more...
 
(.NET Framework also has things like satellite assembles, shims, targeting packs .etc.)

# Displaying Dependencies

Clearly we can't just show all the classes in a graph, as it would simply look overwhelming. If we were to stick to the graph, I'm not sure how to portray the class hierarchy like super classes, and deal with generics.

--- 

Back to the short answer: This is not a goal of DependenSee as it stands today.

I will close this issue, but if there is a case or a different approach I'm missing, happy to hear about it.

**_Thanks for using DependenSee ❤️_**

**Comment by modestotech** [comment]
Big thanks for your reply and your thorough answer, with advice on alternatives. I'll check them out and continue to use dependsee where it shines 🌟
